# Generated by Django 2.2.12 on 2020-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=50)),
                ('resumen', models.TextField()),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Campamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_fin', models.DateField(auto_now_add=True, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Contactar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(default=9)),
                ('email', models.EmailField(max_length=50)),
                ('asunto', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(default=9)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('aforo', models.IntegerField(default=3, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_fin', models.DateField(auto_now_add=True, null=True)),
                ('edad', models.IntegerField(default=10, null=True)),
                ('precio', models.FloatField(default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('imagen', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('wasap', models.IntegerField(default=9)),
                ('imagen', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
