# Generated by Django 2.2.11 on 2020-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campamento',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Campamento', 'verbose_name_plural': 'Campamentos'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'ordering': ['-fecha'], 'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AddField(
            model_name='taller',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
