# Generated by Django 2.2.12 on 2020-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='datos_contacto',
            options={'verbose_name': 'Datos de contacto', 'verbose_name_plural': 'Datos de contacto'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.RenameField(
            model_name='datos_contacto',
            old_name='nombre',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='resumen',
        ),
        migrations.AddField(
            model_name='datos_contacto',
            name='linkWha',
            field=models.URLField(blank=True, null=True, verbose_name='Número de whatsapp'),
        ),
    ]
