# Generated by Django 2.2.12 on 2020-05-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='datos_contacto',
            options={'verbose_name': 'Datos de contacto', 'verbose_name_plural': 'Datos de contacto'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='resumen',
        ),
    ]
