# Generated by Django 3.0.3 on 2020-05-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0002_auto_20200519_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='campamento',
            name='wasap',
            field=models.URLField(blank=True, null=True, verbose_name='Grupo de whatsapp'),
        ),
        migrations.AddField(
            model_name='evento',
            name='wasap',
            field=models.URLField(blank=True, null=True, verbose_name='Grupo de whatsapp'),
        ),
    ]
