# Generated by Django 2.2.11 on 2020-04-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0002_auto_20200428_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactar',
            options={'verbose_name': 'Contactar', 'verbose_name_plural': 'Contactar'},
        ),
        migrations.AlterModelOptions(
            name='datos_contacto',
            options={'verbose_name': 'Datos_contacto', 'verbose_name_plural': 'Datos_contacto'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Datos personales y empresa'},
        ),
        migrations.AlterModelOptions(
            name='opiniones',
            options={'verbose_name': 'Opiniones', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
