# Generated by Django 2.2.11 on 2020-04-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0003_auto_20200428_1601'),
        ('APPWEB', '0002_auto_20200428_0944'),
    ]

    operations = [
    ]
