# Generated by Django 3.0.3 on 2020-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0004_auto_20200524_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(default='imagen', max_length=50),
        ),
    ]
