# Generated by Django 2.2.11 on 2020-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0004_merge_20200430_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campamento',
            name='imagen',
            field=models.ImageField(upload_to='campamento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(upload_to='evento'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='wasap',
            field=models.CharField(max_length=12, verbose_name='Grupo de whatsapp'),
        ),
    ]
