# Generated by Django 2.2.12 on 2020-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0005_auto_20200430_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titular',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='galeria'),
        ),
    ]
