# Generated by Django 2.2.12 on 2020-04-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0006_auto_20200430_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
