# Generated by Django 2.2.12 on 2020-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0007_auto_20200430_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='wasap',
            field=models.URLField(blank=True, null=True, verbose_name='Grupo de whatsapp'),
        ),
    ]
