# Generated by Django 2.2.12 on 2020-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('aforo', models.IntegerField(default=3, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_fin', models.DateField(auto_now_add=True, null=True)),
                ('edad', models.IntegerField(default=10, null=True)),
                ('precio', models.FloatField(default=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contactar',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='taller',
            name='wasap',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='campamento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='opiniones',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
